name: flutter_dro_health_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_bloc: ^6.1.1

  bloc: ^6.1.1

  auto_size_text: ^2.1.0

  equatable: ^1.2.5

  meta: ^1.2.4

  path_provider: ^1.6.27

  simple_animations: ^2.4.2

  uuid: ^2.2.2

  splashscreen: ^1.3.5

  overlay_support: ^1.0.5

  json_annotation: ^3.1.1

  path: ^1.7.0

  sembast: ^2.4.8+1

  dartz: ^0.9.2

  get_it: ^5.0.3

  flutter_dotenv: ^3.0.2
  intl: ^0.16.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.12
  retrofit_generator: ^1.4.1+1
  mockito: ^4.1.3
  json_serializable: ^3.5.1
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/Emzor-Azithromycin-Syrup-15ml.png
    - images/Emzor-Folic-Acid-5mg.png
    - images/Emzor-Paracetamol-Caplets-500mg.png
    - images/FOLIC-ACID.png
    - images/GARLIC-PACK-650mg.png
    - images/Kezitil-500mg-1x10.png
    - images/Kezitil-Cefuroxime-Axetil-Tablets-250mg.png
    - images/Kezitil-suspension-100ml.png
    - images/VITAMIN-E-400-mg.png
    - images/merchant-logo.png
    - images/icons/arrow.png
    - images/icons/drug-bottle.png
    - images/icons/pill.png
    - images/icons/pills.png
    - images/icons/qr-code.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ProximaNova
      fonts:
        - asset: fonts/ProximaNova-Thin.otf
        - asset: fonts/ProximaNova-Regular.otf
        - asset: fonts/ProximaNova-Bold.otf
        - asset: fonts/ProximaNova-ExtraBold.otf
        - asset: fonts/ProximaNova-Black.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
